/*
This JavaScript file exports an asynchronous function unBookMailService that sends a confirmation email for a successful booking cancellation. The email is sent using the mailTransporter from the "../utils/mailtransporter.js" module. The email contains a subject ("Lyckad avbokning") and a text body generated by the textBody function, which simply returns a confirmation message.
*/

import { mailTransporter } from "../utils/mailtransporter.js";

export async function unBookMailService(email) {
  const msg = {
    from: "filmvisarna.grupp1@gmail.com",
    to: email,
    subject: "Lyckad avbokning",
    text: textBody(),
  };

  return mailTransporter.sendMail(msg);
}

function textBody() {
  return `
    Hej! Din avbokning är bekräftad!
    `;
}
